### ISSUE TITLE
Docker registry currently does not allow hyphen character in the namespace

### ISSUE THREAD

**Issue by jwforres** [openshift/docker-registry-extensions#5]
This is problematic for k8s/openshift since our namespaces do allow hyphens, and these namespaces get used automatically when picking the namespace in the docker registry openshift pushes builds to.  Since hyphen is a valid character in a DNS name it should be allowed by docker registry (and is going to be allowed in the next version of the registry).  We will need a workaround in docker-registry-extensions in the mean time.

**Comment by ncdc** [comment]
@jwforres @smarterclayton this isn't a registry issue. The validation error comes from Docker itself. Docker 1.5 allows dashes in namespaces. Docker 1.4 allows underscores, so we might want to consider substitution.

The Docker code is also enforcing namespace lengths, which must be between 4 and 30 characters. I imagine this might cause a problem for us as well, right?

**Comment by smarterclayton** [comment]
By the time we ship 1.4 will be dead - we should definitely make sure newer clients (1.5 and afterwards) work cleanly for us.  Is the namespace length enforced in the registry right now?  Is 30 arbitrary?

----- Original Message -----

**Comment by ncdc** [comment]
30 is enforced in Docker right now. The v1 registry doesn't appear to enforce the 30 character max (or if it does, I didn't find it quickly). The v2 registry definitely does (https://github.com/docker/distribution/blob/master/api/v2/names.go#L16), although v2 will allow 2 to 5 path components for a repository name (which is namespace + name), such as openshift/foo/bar/baz/bingo... at least that's what I get from reading names.go.

**Comment by smarterclayton** [comment]
Can we ask about increasing the limit?

**Comment by ncdc** [comment]
I'll do that and let you know what I find out. How big do we need - 63?

**Comment by smarterclayton** [comment]
Let's ask what use cases they have for limiting.  63 is somewhat arbitrary, but it's a start.

**Comment by ncdc** [comment]
I thought Kubernetes limited namespaces to 63, although now that I'm looking through the code, I see places where it's limited to 24, 63, or 253. Is there a definitive place that says how many characters a namespace can be?

**Comment by smarterclayton** [comment]
We can probably set reasonable limits, but I imagine image names growing very long over time - "sales-division-admin-templates/rhel-python-27-apache-24-mod-wsgi" being a very long name I can think of being not totally unreasonable.

I would like really long names to be possible.  At worst, we can figure out how to solve it.

**Comment by ncdc** [comment]
Requested: https://github.com/docker/docker/issues/10392

**Comment by rqc** [comment]
:+1: For being more lenient with special characters. We are using the open source registry internally and we have LDAP usernames based on our email addresses. For instance we should be able to have a namespace such as jon.doe-smith since we may have a user that has jon.doe-smith@mycompany.com LDAP email address.

**Comment by stevvooe** [comment]
Came here through a google search. I thought we resolved this issue. You may be able to close this.
