### ISSUE TITLE
auth error logged at error level

### ISSUE THREAD

**Issue by sosiouxme** [openshift/docker-registry-extensions#8]
In my OpenShift 3.2 registry I'm getting a number of errors in the registry logs. One that doesn't seem like it should be `level=error` is:

       time="2016-10-10T22:05:53.09732915-04:00" level=error msg="error authorizing context: authorization header with basic token required" go.version=go1.4.2 http.request.host="172.30.248.117:5000" http.request.id=dd935353-7781-4f6b-b042-066db87335ec http.request.method=GET http.request.remoteaddr="10.1.10.1:39413" http.request.uri="/v2/" http.request.useragent="docker/1.10.3 go/go1.4.2 git-commit/7ffc8ee-unsupported kernel/3.10.0-327.13.1.el7.x86_64 os/linux arch/amd64" instance.id=a20494ee-c862-42a0-8893-577e8ef39ed8 
       time="2016-10-10T22:07:26.553102691-04:00" level=error msg="error authorizing context: authorization header with basic token required" go.version=go1.4.2 http.request.host="172.30.248.117:5000" http.request.id=89f60a4d-8adb-4970-bc1c-13588bd17d3b http.request.method=GET http.request.remoteaddr="10.1.13.1:46212" http.request.uri="/v2/" http.request.useragent="docker/1.10.3 go/go1.4.2 git-commit/7ffc8ee-unsupported kernel/3.10.0-327.13.1.el7.x86_64 os/linux arch/amd64" instance.id=a20494ee-c862-42a0-8893-577e8ef39ed8 
       time="2016-10-10T22:07:56.468117847-04:00" level=error msg="error authorizing context: authorization header with basic token required" go.version=go1.4.2 http.request.host="172.30.248.117:5000" http.request.id=24165fad-ae4a-4632-8929-806ba6cf1685 http.request.method=GET http.request.remoteaddr="10.1.12.1:56036" http.request.uri="/v2/" http.request.useragent="docker/1.10.3 go/go1.4.2 git-commit/7ffc8ee-unsupported kernel/3.10.0-327.22.2.el7.x86_64 os/linux arch/amd64" instance.id=a20494ee-c862-42a0-8893-577e8ef39ed8 
       time="2016-10-10T22:11:50.090330658-04:00" level=error msg="error authorizing context: authorization header with basic token required" go.version=go1.4.2 http.request.host="172.30.248.117:5000" http.request.id=72c6db2b-c879-48e7-be75-b0df974ec4ff http.request.method=GET http.request.remoteaddr="10.1.10.1:39634" http.request.uri="/v2/" http.request.useragent="docker/1.10.3 go/go1.4.2 git-commit/7ffc8ee-unsupported kernel/3.10.0-327.13.1.el7.x86_64 os/linux arch/amd64" instance.id=a20494ee-c862-42a0-8893-577e8ef39ed8 
       time="2016-10-10T22:11:57.595052459-04:00" level=error msg="error authorizing context: authorization header with basic token required" go.version=go1.4.2 http.request.host="172.30.248.117:5000" http.request.id=f0d04ba8-3bba-40f4-8577-b1b27b72cd63 http.request.method=GET http.request.remoteaddr="10.1.22.1:54021" http.request.uri="/v2/" http.request.useragent="docker/1.10.3 go/go1.4.2 git-commit/7ffc8ee-unsupported kernel/3.10.0-327.13.1.el7.x86_64 os/linux arch/amd64" instance.id=a20494ee-c862-42a0-8893-577e8ef39ed8 

Diagnostics look through the registry logs for common errors and this doesn't seem like it really merits reporting to the user as an error.

**Comment by ncdc** [comment]
@sosiouxme wrong repo. This one is dead. @smarterclayton @danmcp we should update this repo to indicate it's no longer maintained or used and point people to openshift/origin instead.

**Comment by danmcp** [comment]
@ncdc Done.
